steps:
  # 1️⃣ Terraform Plan & Apply (Infra)
  - name: 'hashicorp/terraform:1.6.0'
    id: 'terraform'
    entrypoint: 'sh'
    dir: 'app/infra'  # Add working directory
    args:
      - '-c'
      - |
        terraform init
        terraform apply -auto-approve

  # 2️⃣ Build and push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - '${_REGION}-docker.pkg.dev/${_BOOTSTRAP_PROJECT_ID}/${_APP_REPO}/${_IMAGE_NAME}:$SHORT_SHA'
      - './app-src'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - '${_REGION}-docker.pkg.dev/${_BOOTSTRAP_PROJECT_ID}/${_APP_REPO}/${_IMAGE_NAME}:$SHORT_SHA'

  # 3️⃣ Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - run
      - deploy
      - '${_APP_NAME}'
      - '--image=${_REGION}-docker.pkg.dev/${_BOOTSTRAP_PROJECT_ID}/${_APP_REPO}/${_IMAGE_NAME}:$SHORT_SHA'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: "us-central1"
  _BOOTSTRAP_PROJECT_ID: "cicdvaibase"
  _APP_REPO: "cicdvaiapp-repo"
  _IMAGE_NAME: "flask-app"
  _APP_NAME: "cicdvai-app"

timeout: 900s
